AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 instances with ALB and Auto Scaling Group

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id

Resources:
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: MySecurityGroup
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  MyTargetGroup:
    Type: 'AWS::ElasticLoadBalancingV2::TargetGroup'
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPort: 80
      HealthCheckPath: /
      TargetType: instance

  MyLoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Scheme: internet-facing
      Subnets:
        - subnet-0c282a6d5e0ce9303
        - subnet-06cd0924941bde9aa
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyLoadBalancer

  MyListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
      LoadBalancerArn: !Ref MyLoadBalancer
      Port: 80
      Protocol: HTTP

  MyAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: MyAutoScalingGroup
      VPCZoneIdentifier:
        - subnet-0c282a6d5e0ce9303
        - subnet-06cd0924941bde9aa
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 2
      DesiredCapacity: 1
      TargetGroupARNs:
        - !Ref MyTargetGroup

  MyLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt MySecurityGroup.GroupId
        ImageId: ami-03bb6d83c60fc5f7c
        InstanceType: t2.micro
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 8
              DeleteOnTermination: true
        UserData:
          Fn::Base64: |
            #!/bin/bash
            sudo apt update -y
            sudo apt install apache2 -y
            sudo ufw allow 'Apache'  
            sudo systemctl enable apache2

  MyScaleUpPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref MyAutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: 1

  MyScaleDownPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName: !Ref MyAutoScalingGroup
      Cooldown: 300
      ScalingAdjustment: -1

  MyCPUAlarmHigh:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Scale-up if CPU > 50% for 5 minutes'
      Namespace: 'AWS/EC2'
      MetricName: 'CPUUtilization'
      Dimensions:
        - Name: 'AutoScalingGroupName'
          Value: !Ref MyAutoScalingGroup
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: 'GreaterThanThreshold'
      AlarmActions:
        - !Ref MyScaleUpPolicy

  MyCPUAlarmLow:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Scale-down if CPU < 50% for 5 minutes'
      Namespace: 'AWS/EC2'
      MetricName: 'CPUUtilization'
      Dimensions:
        - Name: 'AutoScalingGroupName'
          Value: !Ref MyAutoScalingGroup
      Statistic: 'Average'
      Period: 300
      EvaluationPeriods: 1
      Threshold: 50
      ComparisonOperator: 'LessThanThreshold'
      AlarmActions:
        - !Ref MyScaleDownPolicy