Description: Create EC2 instance with custom script and security group

Resources:
  #How to call Stack function.
  MySecurityGroup:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:  https://yourbucket.s3.ap-south-1.amazonaws.com/sg.yaml
  MyInstance:
    Type: AWS::EC2::Instance
    DependsOn:
      - MySecurityGroup
    Properties:
      AvailabilityZone: ap-south-1a
      ImageId: ami-03bb6d83c60fc5f7c  
      InstanceType: t2.micro
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 8
      SecurityGroupIds:
        - !GetAtt MySecurityGroup.Outputs.SecurityGroupIds #Use getAtt to call the function.
      UserData:
        Fn::Base64: |
          #!/bin/bash
          echo "Hello, world! This script runs on boot." > /tmp/hello.txt
